Added error redirect

diff --git a/config_files/ekurc b/config_files/ekurc
--- a/config_files/ekurc
+++ b/config_files/ekurc
@@ -18,7 +18,7 @@ warn() {
 
 error() {
     # Red
-    echo -e "$identifier[\e[31mERROR\e[0m] $*"
+    echo -e "$identifier[\e[31mERROR\e[0m] $*" >&2
 }
 
 success() {
